apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
  labels:
    app: java-backend
spec:
  selector:
    matchLabels:
      app: java-backend
  replicas: 1
  template:
    metadata:
      name: java-backend
      labels:
        app: java-backend
    spec:
      containers:
        - name: java-backend
          image: java-backend:latest # Image that will be used inside the container in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster

---
apiVersion: v1
kind: Service
metadata:
  name: java-backend
  labels:
    app: java-backend
spec:
  type: NodePort
  selector:
    app: java-backend
  ports:
    - name: http
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080