name: CD - Deploy to Minikube using Github Actions
on:
  #Trigger the workflow on push from the master/Github-Actions branch or on pull request
  push:
    branches: [ Github-Actions ]
  pull_request:
    branches: [ Github-Actions ]
jobs:
  # Build job
  job1:
    name: Build and Deploy to Minikube
    # Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t local/devops-demo .
          docker build -f ./webapp/Dockerfile -t local/doc-react ./webapp
          echo -n "Verifying images: "
          docker images
      - name: Deploy to Minikube
        run: |
          kubectl apply -f backend-deployment.yaml,backend-service.yaml,db-persistentvolumeclaim.yaml,db-deployment.yaml,db-service.yaml,web-deployment.yaml,web-service.yaml
          kubectl wait --for=condition=Ready pod -l app=devops-demo
          kubectl wait --for=condition=Ready pod -l app=doc-react
          kubectl get all
      - name: Test service URLs
        run: |
          echo "SERVICE_URL=$(minikube service cicd-example --url)"
          kubectl port-forward service/devops-demo:v405 8080:8080 &> /dev/null &
          sleep 5
          kubectl port-forward service/devops-demo:v405 8080:8080 &> /dev/null &
      - run: |
          curl -i http://localhost:8080/
      - name: Cleanup
        run: |
          eval $(minikube docker-env -u)
          minikube delete