name: CI

on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the master/Github-Actions branch
  push:
    branches: [ Github-Actions ]

jobs:
  #Test's job
  tests:
    name: Unit tests
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
      #Check-out your repository under
      - uses: actions/checkout@v4
      #Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Start PostgreSQL
        uses: docker://postgres:14.1
        env:
          POSTGRES_DB: doc-db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        timeout-minutes: 2
      # Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL
        run: |
          sleep 10 
          while ! pg_isready -h localhost -p 5432 -U postgres -d doc-db; do
            sleep 1
          done
      #Run Tests
      - name: Run Tests
        run: | 
          sleep 10
          mvn -B test
# Build jobs
  build:
    # depends on test's job
    needs: tests
    name: Build
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      #Check-out your repository
      - uses: actions/checkout@v4
      #Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build the application using Maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - run: mkdir staging && cp target/*.jar staging